version: '3.8'

services:
  # MongoDB Service
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # Backend API Service
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/household-gamification
      - JWT_SECRET=your_jwt_secret_change_in_production
      - NODE_ENV=development
      - PORT=5000
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  # Frontend Service
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_APP_NAME=Household Gamification
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    stdin_open: true

# Volumes
volumes:
  mongodb_data:

# Networks
networks:
  app-network:
    driver: bridge
